BEGIN;
TRUNCATE TABLE transactions RESTART IDENTITY CASCADE;
TRUNCATE TABLE tags RESTART IDENTITY CASCADE;
TRUNCATE TABLE transactiontags RESTART IDENTITY CASCADE;
TRUNCATE TABLE category RESTART IDENTITY CASCADE;
TRUNCATE TABLE payee RESTART IDENTITY CASCADE;
TRUNCATE TABLE uploads RESTART IDENTITY CASCADE;
COMMIT;
